// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainBooking.Api.Data;

#nullable disable

namespace TrainBooking.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322103012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainBooking.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("SeatId");

                    b.HasIndex("TrainId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TrainBooking.Api.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainId", "Number")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coach = "A",
                            IsBooked = false,
                            Number = "1A",
                            Row = 1,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 2,
                            Coach = "A",
                            IsBooked = false,
                            Number = "2A",
                            Row = 2,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 3,
                            Coach = "A",
                            IsBooked = false,
                            Number = "3A",
                            Row = 3,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 4,
                            Coach = "A",
                            IsBooked = false,
                            Number = "4A",
                            Row = 4,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 5,
                            Coach = "A",
                            IsBooked = false,
                            Number = "5A",
                            Row = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 6,
                            Coach = "A",
                            IsBooked = false,
                            Number = "6A",
                            Row = 6,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 7,
                            Coach = "A",
                            IsBooked = false,
                            Number = "7A",
                            Row = 7,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 8,
                            Coach = "A",
                            IsBooked = false,
                            Number = "8A",
                            Row = 8,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 9,
                            Coach = "A",
                            IsBooked = false,
                            Number = "9A",
                            Row = 9,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 10,
                            Coach = "A",
                            IsBooked = false,
                            Number = "10A",
                            Row = 10,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 11,
                            Coach = "B",
                            IsBooked = false,
                            Number = "1B",
                            Row = 1,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 12,
                            Coach = "B",
                            IsBooked = false,
                            Number = "2B",
                            Row = 2,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 13,
                            Coach = "B",
                            IsBooked = false,
                            Number = "3B",
                            Row = 3,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 14,
                            Coach = "B",
                            IsBooked = false,
                            Number = "4B",
                            Row = 4,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 15,
                            Coach = "B",
                            IsBooked = false,
                            Number = "5B",
                            Row = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 16,
                            Coach = "B",
                            IsBooked = false,
                            Number = "6B",
                            Row = 6,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 17,
                            Coach = "B",
                            IsBooked = false,
                            Number = "7B",
                            Row = 7,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 18,
                            Coach = "B",
                            IsBooked = false,
                            Number = "8B",
                            Row = 8,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 19,
                            Coach = "B",
                            IsBooked = false,
                            Number = "9B",
                            Row = 9,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 20,
                            Coach = "B",
                            IsBooked = false,
                            Number = "10B",
                            Row = 10,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 21,
                            Coach = "A",
                            IsBooked = false,
                            Number = "1A",
                            Row = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 22,
                            Coach = "A",
                            IsBooked = false,
                            Number = "2A",
                            Row = 2,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 23,
                            Coach = "A",
                            IsBooked = false,
                            Number = "3A",
                            Row = 3,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 24,
                            Coach = "A",
                            IsBooked = false,
                            Number = "4A",
                            Row = 4,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 25,
                            Coach = "A",
                            IsBooked = false,
                            Number = "5A",
                            Row = 5,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 26,
                            Coach = "A",
                            IsBooked = false,
                            Number = "6A",
                            Row = 6,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 27,
                            Coach = "A",
                            IsBooked = false,
                            Number = "7A",
                            Row = 7,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 28,
                            Coach = "A",
                            IsBooked = false,
                            Number = "8A",
                            Row = 8,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 29,
                            Coach = "A",
                            IsBooked = false,
                            Number = "9A",
                            Row = 9,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 30,
                            Coach = "A",
                            IsBooked = false,
                            Number = "10A",
                            Row = 10,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 31,
                            Coach = "B",
                            IsBooked = false,
                            Number = "1B",
                            Row = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 32,
                            Coach = "B",
                            IsBooked = false,
                            Number = "2B",
                            Row = 2,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 33,
                            Coach = "B",
                            IsBooked = false,
                            Number = "3B",
                            Row = 3,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 34,
                            Coach = "B",
                            IsBooked = false,
                            Number = "4B",
                            Row = 4,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 35,
                            Coach = "B",
                            IsBooked = false,
                            Number = "5B",
                            Row = 5,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 36,
                            Coach = "B",
                            IsBooked = false,
                            Number = "6B",
                            Row = 6,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 37,
                            Coach = "B",
                            IsBooked = false,
                            Number = "7B",
                            Row = 7,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 38,
                            Coach = "B",
                            IsBooked = false,
                            Number = "8B",
                            Row = 8,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 39,
                            Coach = "B",
                            IsBooked = false,
                            Number = "9B",
                            Row = 9,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 40,
                            Coach = "B",
                            IsBooked = false,
                            Number = "10B",
                            Row = 10,
                            TrainId = 2
                        });
                });

            modelBuilder.Entity("TrainBooking.Api.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2026, 4, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            DepartureTime = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Ho Chi Minh City",
                            Name = "Express 101",
                            Origin = "Hanoi"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2026, 4, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            DepartureTime = new DateTime(2026, 4, 2, 7, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Da Nang",
                            Name = "Express 202",
                            Origin = "Ho Chi Minh City"
                        });
                });

            modelBuilder.Entity("TrainBooking.Api.Models.Booking", b =>
                {
                    b.HasOne("TrainBooking.Api.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainBooking.Api.Models.Train", "Train")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainBooking.Api.Models.Seat", b =>
                {
                    b.HasOne("TrainBooking.Api.Models.Train", "Train")
                        .WithMany("Seats")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainBooking.Api.Models.Train", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
